@startuml
'https://plantuml.com/sequence-diagram

class Main{
    +main(String[]args):void
}
class WordTrainer {
    -<linkedList>WordPair:
    -numAskeskedQ:int
    -correctQ:int


    +save(): void
    +load(): void
    +check(): boolean
    +stats(): String
}

class WordPair {
    - word
    - url
    +WordPair(word: String,url:String)
    +checkURL(): boolean
    + toString():String


}

class Gui {
    + drawGUI()

}

file file{

}

WordTrainer --> WordPair: uses 1..*
WordTrainer --> Gui:1..1
WordTrainer <--> file:1..1
Main -->WordTrainer: 1..*


@enduml
