@startuml
'https://plantuml.com/sequence-diagram


class Main {
    -<linkedList>WordPair:
    -numAskeskedQ:int
    -correctQ:int

    + main() : void
    +save(): void
    +load(): void
    +check(): boolean
    +stats(): String
}

class WordPair {
    - word
    - url
    +WordPair(word: String,url:String)
    +checkURL(): boolean
    + toString():String


}

class Gui {
    + drawGUI()

}

file file{

}

Main --> WordPair: uses 1..*
Main --> Gui
Main <--> file: saves Stats


@enduml
