@startuml
'https://plantuml.com/sequence-diagram

class Main{
    +main(String[]args):void
}
class WordTrainer {
    -<linkedList>WordPair:

    +check(): boolean
}

class WordPair {
    - word
    - url
    +WordPair(word: String,url:String)
    +WordPair()
    +checkURL(): boolean
    + toString():String
    + getWord(): String
    + getUrl(): String


}

class Gui {
    -correctCount
    -attempts
    -falseCount
    + Gui()
    + displayImage(): void


}
class JFrame{
}
interface PersistanceStrategy{
    +save(): void
    +load(): void
}
class SaveJson{
    +save(): void
    +load(): void
}

file file{

}

WordTrainer o-- WordPair: uses 1..*
Gui --> WordTrainer
Gui o--> PersistanceStrategy
SaveJson <--> file:1..1
Main --> Gui: 1
SaveJson ..|> PersistanceStrategy
Gui --|> JFrame


@enduml
